openapi: 3.0.4
info:
  title: Periodic Table
  description: Periodic Table is a simple tool for getting information about chemical elements. It returns information such as the atomic number, symbol, and more based on the element provided.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/periodictable:
    get:
      summary: Get Element Information by Name
      description: Periodic Table is a simple tool for getting information about chemical elements. It returns information such as the atomic number, symbol, and more based on the element provided.
      operationId: periodictable
      parameters:
      - name: name
        in: query
        schema:
          type: string
        required: true
        description: The name of the chemical element to get information about
        example: hydrogen
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  name: Hydrogen
                  appearance: colorless gas
                  atomic_mass: 1.008
                  boil: 20.271
                  category: diatomic nonmetal
                  density: 0.08988
                  discovered_by: Henry Cavendish
                  melt: 13.99
                  molar_heat: 28.836
                  named_by: Antoine Lavoisier
                  number: 1
                  period: 1
                  group: 1
                  phase: Gas
                  source: https://en.wikipedia.org/wiki/Hydrogen
                  summary: Hydrogen is a chemical element with chemical symbol H and atomic number 1. With an atomic weight of 1.00794 u, hydrogen is the lightest element on the periodic table. Its monatomic form (H) is the most abundant chemical substance in the Universe, constituting roughly 75% of all baryonic mass.
                  symbol: H
                  xpos: 1
                  ypos: 1
                  wxpos: 1
                  wypos: 1
                  shells:
                  - 1
                  electron_configuration: 1s1
                  electron_configuration_semantic: 1s1
                  electron_affinity: 72.769
                  electronegativity_pauling: 2.2
                  ionization_energies:
                  - 1312
                  cpk-hex: ffffff
                  block: s
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
